Repository RedHatInsights/ros-frontend, pull requests merged in 2021-12, with the labels that each got.

#76 RHIROS-421 - added new state 'Under pressure' for system
  src/Components/RosTable/SystemState.js
Labels: waiting for backend, ready for review

#77 RHIROS-379 show rules content with newline and tab space
  src/Components/SystemDetail/RecommendationsTable.js
  src/Components/SystemDetail/RecommendationsTable.scss
  src/Components/SystemDetail/__snapshots__/RecommendationsTable.test.js.snap
Labels: waiting for backend

#79 RHIROS-421 updated under-pressure state icon color
  src/Components/RosTable/SystemState.js
Labels: ready for review

#75 updated render method for disk usage to show number instead of progress bar
  src/Components/RosTable/DiskUsage.js
  src/Components/RosTable/DiskUsage.scss
  src/Routes/RosPage/RosPage.js
Labels: ready for review
