Repository RedHatInsights/ros-frontend, pull requests merged in 2022-04, with the labels that each got.

#103 Export systems report PDF/CSV/JSON
  package-lock.json
  package.json
  src/Components/Reports/Common/styles.js
  src/Components/Reports/DownloadReport.js
  src/Components/Reports/SystemsPDFReport.js
  src/Components/Reports/Util.js
  src/Components/Reports/Util.test.js
  src/Components/Reports/UtilTestData.js
  src/Routes/RosPage/RosPage.js
  src/Routes/RosPage/ros-page.scss
  src/Utilities/api.js
  src/constants.js
Labels: ready for review

#106 RHIROS 606 fix pdf page numbering
  package.json
  src/Components/Reports/Common/SystemsFirstPage.js
  src/Components/Reports/Common/SystemsFirstPage.test.js
  src/Components/Reports/Common/SystemsTablePage.js
  src/Components/Reports/Common/SystemsTablePage.test.js
  src/Components/Reports/Common/__snapshots__/SystemsFirstPage.test.js.snap
  src/Components/Reports/Common/__snapshots__/SystemsTablePage.test.js.snap
  src/Components/Reports/SystemsPDFReport.js
  src/constants.js
Labels: ready for review

#107 Rhiros 579 add report date
  package-lock.json
  package.json
  src/Components/Reports/Common/SystemsTablePage.js
  src/Components/Reports/Common/__snapshots__/SystemsFirstPage.test.js.snap
  src/Components/Reports/Common/__snapshots__/SystemsTablePage.test.js.snap
  src/Components/Reports/Util.js
  src/Components/Reports/Util.test.js
  src/Components/Reports/UtilTestData.js
  src/Components/RosTable/RenderColumn.js
  src/Routes/RosPage/RosPage.js
  src/Utilities/api.js
  src/constants.js
Labels: ready for review

#113 Ref-RHIROS-579 code refactoring: DateFormat component from FEC
  package-lock.json
  package.json
  src/Components/Reports/Util.js
  src/Components/Reports/Util.test.js
  src/Components/Reports/UtilTestData.js
  src/Components/RosTable/RenderColumn.js
  src/constants.js
Labels: ready for review

#110 RHIROS #533 - Apply filtering on OS column
  src/Routes/RosPage/RosPage.js
  src/constants.js
Labels: ready for review

#114 RHIROS-625 fix reported date format in reports
  src/Components/Reports/Common/SystemsTablePage.js
  src/Components/Reports/Common/__snapshots__/SystemsFirstPage.test.js.snap
  src/Components/Reports/Common/__snapshots__/SystemsTablePage.test.js.snap
  src/Components/Reports/Common/styles.js
  src/Components/Reports/Util.js
  src/Components/Reports/Util.test.js
Labels: ready for review

#112 RHIROS-605 added download alert for different states
  src/Components/Reports/DownloadReport.js
  src/Components/Reports/SystemsPDFReport.js
  src/Routes/RosPage/RosPage.js
  src/constants.js
Labels: ready for review

#116 RHIROS-610 - OS filter info in PDF report
  src/Components/Reports/DownloadReport.js
  src/Components/Reports/SystemsPDFReport.js
  src/Components/Reports/Util.js
  src/Components/Reports/Util.test.js
  src/Routes/RosPage/RosPage.js
  src/Utilities/api.js
Labels: waiting for QE, do not merge, approved

#115 Rhiros 142 show historical data
  package-lock.json
  package.json
  src/Components/HistoricalDataChart/HistoricalDataChart.js
  src/Components/HistoricalDataChart/HistoricalDataChart.scss
  src/Components/HistoricalDataChart/Util.js
  src/Components/HistoricalDataChart/Util.test.js
  src/Components/HistoricalDataChart/UtilTestData.js
  src/Components/Reports/Util.test.js
  src/Routes/RosSystemDetail/RosSystemDetail.js
  src/Routes/RosSystemDetail/ros-details-page.scss
  src/Utilities/api.js
  src/constants.js
Labels: waiting for QE, do not merge, ready for review

#119 Prod beta --- > Prod Stable
  package-lock.json
  package.json
  src/Components/Reports/Common/SystemsFirstPage.js
  src/Components/Reports/Common/SystemsFirstPage.test.js
  src/Components/Reports/Common/SystemsTablePage.js
  src/Components/Reports/Common/SystemsTablePage.test.js
  src/Components/Reports/Common/__snapshots__/SystemsFirstPage.test.js.snap
  src/Components/Reports/Common/__snapshots__/SystemsTablePage.test.js.snap
  src/Components/Reports/Common/styles.js
  src/Components/Reports/DownloadReport.js
  src/Components/Reports/SystemsPDFReport.js
  src/Components/Reports/Util.js
  src/Components/Reports/Util.test.js
  src/Components/Reports/UtilTestData.js
  src/Components/RosTable/RenderColumn.js
  src/Components/SystemDetail/RecommendationsTable.js
  src/Components/SystemDetail/RecommendationsTable.scss
  src/Components/SystemDetail/__snapshots__/RecommendationsTable.test.js.snap
  src/Routes/RosPage/RosPage.js
  src/Routes/RosPage/ros-page.scss
  src/Utilities/api.js
  src/constants.js
Labels: waiting for QE, do not merge, ready for review
